In [ ]:
# part 1

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)

print(nx, ny)

board = np.array([[{'.': 0, '#': 1, 'S': 5, 'E': 9}[x] for x in row] for row in rows], dtype=np.int8)
ys, xs = np.array(np.where(board == 5))[:, 0]
ye, xe = np.array(np.where(board == 9))[:, 0]
board[ys, xs], board[ye, xe] = 0, 0

print(board)

def valid_point(point):
    return 0 <= point[0] < ny and 0 <= point[1] < nx


def find_next(point, prev_point):
    y, x = point 
    adjacent = [(y-1, x), (y+1, x), (y, x+1), (y, x-1)]
    for point in adjacent:
        if valid_point(point) and not point == prev_point:
            if board[point] == 0:
                return point
                
# first we try to find the normal path
y, x = ys, xs
prev_y, prev_x = 0, 0

point = y, x 
prev_point = prev_y, prev_x
path = [point]
while point != (ye, xe):

    new_point = find_next(point, prev_point)

    prev_point = point
    point = new_point
    path.append(point)


print(len(path))

cheats = []

def dst(pointa, pointb):
    return abs(pointa[0] - pointb[0]) + abs(pointa[1] - pointb[1])

for i in range(len(path)):
    for j in range(i + 3, len(path)):
        #print(i, j, dst(path[i], path[j]))
        if dst(path[i], path[j]) <= 2:
            cheats.append(j - i - 2)

print(cheats)

if filename == 'test.txt':
    print(cheats.count(2))
    print(cheats.count(4))
    print(cheats.count(6))
    print(cheats.count(8))

    print(cheats.count(10))
    print(cheats.count(12))

    print(cheats.count(20))
    print(cheats.count(36))
    print(cheats.count(38))
    print(cheats.count(40))


print(len(list(filter(lambda x: x>= 100, cheats))))

In [ ]:
# part 2 test

import os, re, sys
import numpy as np

filename = "test.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)

print(nx, ny)

board = np.array([[{'.': 0, '#': 1, 'S': 5, 'E': 9}[x] for x in row] for row in rows], dtype=np.int8)
ys, xs = np.array(np.where(board == 5))[:, 0]
ye, xe = np.array(np.where(board == 9))[:, 0]
board[ys, xs], board[ye, xe] = 0, 0

print(board)

def valid_point(point):
    return 0 <= point[0] < ny and 0 <= point[1] < nx


def find_next(point, prev_point):
    y, x = point 
    adjacent = [(y-1, x), (y+1, x), (y, x+1), (y, x-1)]
    for point in adjacent:
        if valid_point(point) and not point == prev_point:
            if board[point] == 0:
                return point
                
# first we try to find the normal path
y, x = ys, xs
prev_y, prev_x = 0, 0

point = y, x 
prev_point = prev_y, prev_x
path = [point]
while point != (ye, xe):
    new_point = find_next(point, prev_point)
    prev_point = point
    point = new_point
    path.append(point)




cheats = []

def dst(pointa, pointb):
    return abs(pointa[0] - pointb[0]) + abs(pointa[1] - pointb[1])

for i in range(len(path)):
    for j in range(i + 43, len(path)):
        #print(i, j, dst(path[i], path[j]))
        if dst(path[i], path[j]) <= 20:
            gain = j - i - dst(path[i], path[j])
            if gain >= 40:
                cheats.append(gain)


if filename == 'test.txt':
    print(cheats.count(64))
    print(cheats.count(66))
    print(cheats.count(68))
    print(cheats.count(70))
    print(cheats.count(72))
    print(cheats.count(74))
    print(cheats.count(76))


15 15
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 1 0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1 0 1 0 0 0 1]
 [1 1 1 1 1 1 1 0 1 0 1 0 1 1 1]
 [1 1 1 1 1 1 1 0 1 0 1 0 0 0 1]
 [1 1 1 1 1 1 1 0 1 0 1 1 1 0 1]
 [1 1 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [1 1 1 0 1 1 1 1 1 1 1 0 1 1 1]
 [1 0 0 0 1 1 1 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0 1 0 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1 0 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 1 1]
 [1 0 0 0 1 0 0 0 1 0 0 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
19
12
14
12
22
4
3


In [ ]:
# part 2 (real data, but inefficient)

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)

print(nx, ny)

board = np.array([[{'.': 0, '#': 1, 'S': 5, 'E': 9}[x] for x in row] for row in rows], dtype=np.int8)
ys, xs = np.array(np.where(board == 5))[:, 0]
ye, xe = np.array(np.where(board == 9))[:, 0]
board[ys, xs], board[ye, xe] = 0, 0

print(board)

def valid_point(point):
    return 0 <= point[0] < ny and 0 <= point[1] < nx


def find_next(point, prev_point):
    y, x = point 
    adjacent = [(y-1, x), (y+1, x), (y, x+1), (y, x-1)]
    for point in adjacent:
        if valid_point(point) and not point == prev_point:
            if board[point] == 0:
                return point

# first we try to find the normal path
y, x = ys, xs
prev_y, prev_x = 0, 0

point = y, x 
prev_point = prev_y, prev_x
path = [point]
while point != (ye, xe):
    new_point = find_next(point, prev_point)
    prev_point = point
    point = new_point
    path.append(point)


def dst(pointa, pointb):
    return abs(pointa[0] - pointb[0]) + abs(pointa[1] - pointb[1])

count = 0
for i in range(len(path)):
    for j in range(i + 100, len(path)):
        if dst(path[i], path[j]) <= 20:
            gain = j - i - dst(path[i], path[j])
            if gain >= 100:
                count += 1

print(count)


141 141
[[1 1 1 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [1 0 1 ... 1 0 1]
 ...
 [1 0 1 ... 1 0 1]
 [1 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 1]]
1017615


In [ ]:
# part 2 more efficient

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)
board = np.array([[{'.': 0, '#': 1, 'S': 5, 'E': 9}[x] for x in row] for row in rows], dtype=np.int8)
ys, xs = np.array(np.where(board == 5))[:, 0]
ye, xe = np.array(np.where(board == 9))[:, 0]
board[ys, xs], board[ye, xe] = 0, 0

def valid_point(point):
    return 0 <= point[0] < ny and 0 <= point[1] < nx

def find_next(point, prev_point):
    y, x = point 
    adjacent = [(y-1, x), (y+1, x), (y, x+1), (y, x-1)]
    for point in adjacent:
        if valid_point(point) and not point == prev_point:
            if board[point] == 0:
                return point

# first we try to find the normal path
y, x = ys, xs
prev_y, prev_x = 0, 0

point = y, x 
prev_point = prev_y, prev_x
path = {point: 0}
i = 0
while point != (ye, xe):
    new_point = find_next(point, prev_point)
    prev_point = point
    point = new_point

    i += 1
    path[point] = i

d = 20 # max timeout
count = 0
def search_shortcuts(y, x):
    global count, d
    current = path[y, x]
    for dy in range(-d, d + 1):
        for dx in range(-d + abs(dy), d - abs(dy) + 1):
            newy, newx = y + dy, x + dx
            if valid_point((newy, newx)):
                if board[newy, newx] == 0:
                    gain = path[newy, newx] - current - abs(newy - y) - abs(newx - x)
                    count += int(gain >= 100)

for y in range(ny):
    for x in range(nx):
        if board[y, x] == 0:
            search_shortcuts(y, x)


