In [22]:
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx = len(rows[0])
ny = len(rows)
board = np.zeros((ny, nx), dtype=int)

for j in range(ny):
    for i in range(nx):
        board[j][i] = int(rows[j][i])

print(board)


def in_board(y, x):
    if x >= 0 and y >=0 and x < nx and y < ny:
        return True

def search_path(val, y, x, reached=[]):

    # edge case; reached the final 9
    if val == 9:
        if (y, x) not in reached:
            reached.append((y, x))
            return 1
        
        # we already have this 0-9 combination so no need to add it
        else:
            return 0
    
    # check all 4 adjacent squares, add all the paths they can generate
    total = 0   
    contiguous = [(y, x+1), (y, x-1), (y+1, x), (y-1, x)]
    for new_pos in contiguous:
        y, x = new_pos
        if in_board(y, x):
            if board[y, x] == val + 1:
                total += search_path(val + 1, y, x, reached)
                
    return total


# for every 0 on the map execute recursive function
count = 0
for j in range(ny):
    for i in range(nx):
        if board[j][i] == 0:
            count += search_path(0, j, i, [])

print(count)



[[3 2 1 ... 8 7 6]
 [7 3 0 ... 3 4 5]
 [8 9 4 ... 7 3 0]
 ...
 [8 5 4 ... 3 2 7]
 [9 2 3 ... 8 9 8]
 [0 1 0 ... 7 8 7]]
510


In [24]:
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx = len(rows[0])
ny = len(rows)
board = np.zeros((ny, nx), dtype=int)

for j in range(ny):
    for i in range(nx):
        board[j][i] = int(rows[j][i])

print(board)


def in_board(y, x):
    if x >= 0 and y >=0 and x < nx and y < ny:
        return True

def search_path(val, y, x):
    if val == 9:
        return 1
    
    total = 0   
    contiguous = [(y, x+1), (y, x-1), (y+1, x), (y-1, x)]
    for new_pos in contiguous:
        y, x = new_pos
        if in_board(y, x):
            if board[y, x] == val + 1:
                total += search_path(val + 1, y, x)
    return total



count = 0
for j in range(ny):
    for i in range(nx):
        if board[j][i] == 0:
            count += search_path(0, j, i)
            
print(count)



[[3 2 1 ... 8 7 6]
 [7 3 0 ... 3 4 5]
 [8 9 4 ... 7 3 0]
 ...
 [8 5 4 ... 3 2 7]
 [9 2 3 ... 8 9 8]
 [0 1 0 ... 7 8 7]]
1058
