In [42]:
# part 1

import os, re, sys
import numpy as np
import math

filename = "test.txt"
with open(filename, 'r') as f:
    s = f.read()
    
startcodes = [int(x) for x in s.split("\n")]
print(startcodes)


def step1(secr):
    return ((64 * secr) ^ secr) % 16777216

def step2(secr):
    return (math.floor(secr / 32) ^ secr) % 16777216

def step3(secr):
    return ((2048 * secr) ^ secr) % 16777216


#startcodes = [123]
n = 2000

startcodes = [1, 2, 3, 2024]

prices = np.zeros((len(startcodes), n+1), dtype=int)
deltas = np.zeros((len(startcodes), n), dtype=int)



total_score = 0
for code_i in range(len(startcodes)):
    secret = startcodes[code_i]
    price = str(secret)[-1]

    prices[code_i][0] = price

    for i in range(n):
        secret = step3(step2(step1(secret)))
        price = int(str(secret)[-1])

        prices[code_i, i+1] = price
        deltas[code_i, i] = prices[code_i, i+1] - prices[code_i, i]

    total_score += secret

print(total_score)




def calculate_policy(series):
    total = 0
    for i in range(len(startcodes)):
        j = 0
        while j < n - 3:
            if (deltas[i, j:j+4] == series).all():
                total += prices[i, j + 4]
                print(prices[i, j + 4])
                break
            j += 1
    
    print(total)
    return total


print(calculate_policy(np.array([-2, 1, -1, 3])))

print(prices)
print(deltas)

[1, 10, 100, 2024]
37990510
7
7
9
23
23
[[1 3 3 ... 3 2 9]
 [2 6 2 ... 6 6 3]
 [3 3 3 ... 3 8 4]
 [4 9 5 ... 1 8 4]]
[[ 2  0  6 ...  3 -1  7]
 [ 4 -4  2 ...  1  0 -3]
 [ 0  0 -2 ...  2  5 -4]
 [ 5 -4 -2 ... -6  7 -4]]


In [46]:

# part 1

import os, re, sys
import numpy as np
import math

filename = "test.txt"
with open(filename, 'r') as f:
    s = f.read()
    
startcodes = [int(x) for x in s.split("\n")]
print(startcodes)


def step1(secr):
    return ((64 * secr) ^ secr) % 16777216

def step2(secr):
    return (math.floor(secr / 32) ^ secr) % 16777216

def step3(secr):
    return ((2048 * secr) ^ secr) % 16777216


#startcodes = [123]
n = 2000

startcodes = [1, 2, 3, 2024]

prices = np.zeros((len(startcodes), n+1), dtype=int)
deltas = np.zeros((len(startcodes), n), dtype=int)



total_score = 0
for code_i in range(len(startcodes)):
    secret = startcodes[code_i]
    price = str(secret)[-1]

    prices[code_i][0] = price

    for i in range(n):
        secret = step3(step2(step1(secret)))
        price = int(str(secret)[-1])

        prices[code_i, i+1] = price
        deltas[code_i, i] = prices[code_i, i+1] - prices[code_i, i]

    total_score += secret

print(total_score)




def calculate_policy(series):
    total = 0
    for i in range(len(startcodes)):
        j = 0
        while j < n - 3:
            if (deltas[i, j:j+4] == series).all():
                total += prices[i, j + 4]
                #print(prices[i, j + 4])
                break
            j += 1
    return total



max_s = 0
best_s = 0
for a in range(-9, 10):
    print("a = ", a)
    for b in range(-9, 10):
        print("b = ", b)
        for c in range(-9, 10):
            for d in range(-9, 10):
                s = calculate_policy(np.array([a, b, c, d]))
                if s > max_s:
                    max_s = s
                    best_s = np.array([a, b, c, d])

print(best_s, max_s)
print(calculate_policy(np.array([-2, 1, -1, 3])))

print(prices)
print(deltas)

[1, 10, 100, 2024]
37990510
a =  -9
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -8
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -7
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -6
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -5
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -4
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
b =  -1
b =  0
b =  1
b =  2
b =  3
b =  4
b =  5
b =  6
b =  7
b =  8
b =  9
a =  -3
b =  -9
b =  -8
b =  -7
b =  -6
b =  -5
b =  -4
b =  -3
b =  -2
