In [35]:

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)


board = np.array([[1 if x == "#" else 0 for x in row ] for row in rows], dtype=int)

print(board)

y, x, d = ny - 2, 1, 0 # start  
goal_y, goal_x = 1, nx - 2

location_cost = np.full((ny, nx, 4), 0, dtype=int)
location_cost[y, x, :] = [1000, 0, 1000, 2000]

#cost_location = {1000: (x,y,0), 0: (x,y,1), 1000: (x,y,2), 2000: (x,y,3)}


new_locs = [(y, x, d)]


def find_smallest():
    minimum = np.inf
    minloc = None
    for loc in new_locs:
        y, x, d = loc
        val = location_cost[y, x, d]
        if val < minimum:
            minimum = val
            minloc = loc
    return minloc


rotation_costs = np.array([0, 1000, 2000])

dirs = np.array([[-1, 0], [0, 1], [1, 0], [0, -1]])

def update(loc):
    y, x, d = loc
    dy, dx = dirs[d]
    ny, nx = y + dy, x + dx
    
    cost = location_cost[y, x, d]
    new_locs.remove((y, x, d))
    if not board[ny, nx]: # this is empty            
        for j in range(4):
            if location_cost[ny, nx, j] > cost + rotation_costs[(d - j) % 2] + 1 or location_cost[ny, nx, j] == 0:
                new_locs.append((ny, nx, j))
                location_cost[ny, nx, j] = cost + rotation_costs[(d - j) % 2] + 1

print(location_cost.shape)

while True:
    if max(location_cost[goal_y, goal_x]) > 0:
        print(location_cost[goal_y, goal_x]); break
    #print(location_cost[:, :, 0])
    update(find_smallest())





[[1 1 1 ... 1 1 1]
 [1 0 1 ... 0 0 1]
 [1 0 1 ... 1 0 1]
 ...
 [1 0 1 ... 1 0 1]
 [1 0 0 ... 1 0 1]
 [1 1 1 ... 1 1 1]]
(141, 141, 4)
[91440 90440 91440 90440]


In [61]:

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)


board = np.array([[1 if x == "#" else 0 for x in row ] for row in rows], dtype=int)

print(board)

y, x, d = ny - 2, 1, 0 # start  
goal_y, goal_x = 1, nx - 2

location_cost = np.full((ny, nx, 4), 0)#, dtype=int)
location_cost[y, x, :] = [1000, 0, 1000, 2000]

new_locs = [(y, x, d)]

shortest_way = {(y, x, d): []}


def find_smallest():
    minimum = np.inf
    minloc = None
    for loc in new_locs:
        y, x, d = loc
        val = location_cost[y, x, d]
        if val < minimum:
            minimum = val
            minloc = loc
    return minloc


rotation_costs = np.array([0, 1000, 2000, 1000])

dirs = np.array([[-1, 0], [0, 1], [1, 0], [0, -1]])

def update(loc):
    
    y, x, d = loc
    dy, dx = dirs[d]
    ny, nx = y + dy, x + dx
    
    cost = location_cost[y, x, d]
    new_locs.remove((y, x, d))
    if not board[ny, nx]: # this is empty            
        for j in range(4):
            if location_cost[ny, nx, j] == cost + rotation_costs[abs(d - j)] + 1:
                shortest_way[(int(ny), int(nx), j)].append((int(y), int(x), d))
                location_cost[ny, nx, j] = cost + rotation_costs[abs(d - j)] + 1
                continue
            elif location_cost[ny, nx, j] > cost + rotation_costs[abs(d - j)] + 1 or location_cost[ny, nx, j] == 0:
                new_locs.append((ny, nx, j))
                shortest_way[(int(ny), int(nx), j)] = [(int(y), int(x), d)]
                location_cost[ny, nx, j] = cost + rotation_costs[abs(d - j)] + 1
            

print(location_cost.shape)





map = [[int(board[y, x]) for x in range(nx)] for y in range(ny)]
def reconstruct():
    minimum = 100000000000
    minidx = None
    for i in range(4):
        #print(location_cost[goal_y, goal_x, i])
        if location_cost[goal_y, goal_x, i] < minimum:
            minimum = location_cost[goal_y, goal_x, i]
            minidx = [i]
        elif location_cost[goal_y, goal_x, i] == minimum:
            minidx.append(i)

    locations = [(goal_y, goal_x, i) for i in minidx]
    new_locs = [(goal_y, goal_x, i) for i in minidx]

    print(minidx)

    while new_locs:
        print(new_locs)
        loc = new_locs.pop()
        prev = shortest_way[loc]
        locations += prev
        new_locs += prev
        
    
    print(len(locations))

    count = 0
    for i in range(len(locations)):
        for j in range(i):
            if locations[i][:2] == locations[j][:2]:
                break
        else:
            map[locations[i][0]][locations[i][1]] = 8
            count += 1
    print(count)



    

while True:
    if max(location_cost[goal_y, goal_x]) > 0:
        print(location_cost[goal_y, goal_x]); break
    #print(location_cost[:, :, 0])
    update(find_smallest())



for key in shortest_way:
    #print(key, shortest_way[key])
    pass
reconstruct()


# print map
print('')
for line in map:
    for char in line:
        print({0: " ", 1: "O", 8: "+"}[char], end='')
    print('')
print('')
# 466 is too low


[[1 1 1 ... 1 1 1]
 [1 0 1 ... 0 0 1]
 [1 0 1 ... 1 0 1]
 ...
 [1 0 1 ... 1 0 1]
 [1 0 0 ... 1 0 1]
 [1 1 1 ... 1 1 1]]
(141, 141, 4)
[91440 90440 91440 92440]
[1]
[(1, 139, 1)]
[(1, 138, 1)]
[(1, 137, 1)]
[(1, 136, 1)]
[(1, 135, 1)]
[(1, 134, 1)]
[(1, 133, 1)]
[(1, 132, 1)]
[(1, 131, 1)]
[(2, 131, 0)]
[(3, 131, 0)]
[(3, 130, 1)]
[(3, 129, 1)]
[(2, 129, 2)]
[(1, 129, 2)]
[(1, 128, 1)]
[(1, 127, 1)]
[(2, 127, 0)]
[(3, 127, 0)]
[(4, 127, 0)]
[(5, 127, 0)]
[(6, 127, 0)]
[(7, 127, 0)]
[(8, 127, 0)]
[(9, 127, 0)]
[(10, 127, 0)]
[(11, 127, 0)]
[(12, 127, 0)]
[(13, 127, 0)]
[(14, 127, 0)]
[(15, 127, 0)]
[(15, 128, 3), (16, 127, 0)]
[(15, 128, 3), (17, 127, 0)]
[(15, 128, 3), (17, 128, 3)]
[(15, 128, 3), (17, 129, 3)]
[(15, 128, 3), (18, 129, 0)]
[(15, 128, 3), (19, 129, 0)]
[(15, 128, 3), (20, 129, 0)]
[(15, 128, 3), (21, 129, 0)]
[(15, 128, 3), (22, 129, 0)]
[(15, 128, 3), (23, 129, 0)]
[(15, 128, 3), (24, 129, 0)]
[(15, 128, 3), (25, 129, 0)]
[(15, 128, 3), (26, 129, 0)]
[(15, 128, 3), (27,

In [ ]:

import os, re, sys
import numpy as np

filename = "data.txt"
with open(filename, 'r') as f:
    s = f.read()
    rows = s.split("\n")

nx, ny = len(rows[0]), len(rows)

board = np.array([[1 if x == "#" else 0 for x in row ] for row in rows], dtype=int)

print(board)

y, x, d = ny - 2, 1, 0 # start  
goal_y, goal_x = 1, nx - 2

location_cost = np.full((ny, nx, 4), 0, dtype=int)
location_cost[y, x, :] = [1000, 0, 1000, 2000]


new_locs = [(y, x, d)]


def find_smallest():
    minimum = np.inf
    minloc = None
    for loc in new_locs:
        y, x, d = loc
        val = location_cost[y, x, d]
        if val < minimum:
            minimum = val
            minloc = loc
    return minloc


rotation_costs = np.array([0, 1000, 2000, 1000])

dirs = np.array([[-1, 0], [0, 1], [1, 0], [0, -1]])

def update(loc):
    y, x, d = loc
    dy, dx = dirs[d]
    ny, nx = y + dy, x + dx
    
    cost = location_cost[y, x, d]
    new_locs.remove((y, x, d))
    if not board[ny, nx]: # this is empty            
        for j in range(4):

            if d - j == 3:
                val = 1
            else: val = abs(d - j)

            if location_cost[ny, nx, j] > cost + rotation_costs[abs(d - j)] + 1 or location_cost[ny, nx, j] == 0:
                new_locs.append((ny, nx, j))
                location_cost[ny, nx, j] = cost + rotation_costs[abs(d - j)] + 1

print(location_cost.shape)


map = [[int(board[y, x]) for x in range(nx)] for y in range(ny)]

def reconstruct():
    minimum = 100000000000
    minidx = None
    for i in range(4):
        #print(location_cost[goal_y, goal_x, i])
        if location_cost[goal_y, goal_x, i] < minimum:
            minimum = location_cost[goal_y, goal_x, i]
            minidx = [i]
        elif location_cost[goal_y, goal_x, i] == minimum:
            minidx.append(i)

    locations = [(goal_y, goal_x, i) for i in minidx]
    new_locs = [(goal_y, goal_x, i) for i in minidx]
    
    while new_locs:
        print(new_locs)
        loc = new_locs.pop()
        y, x, d = loc
        cost = location_cost[y, x, d]
        possible_prev = [(y + 1, x, 0), (y, x - 1, 1), (y - 1, x, 2), (y, x + 1, 3)]
        for i in range(len(possible_prev)):
            prev = possible_prev[i]
            if location_cost[prev] == cost - 1 - rotation_costs[abs(i - d)] and location_cost[prev] != 0:
                new_locs.append(prev)
                locations.append(prev)
                #print(loc, prev)
                
                map[prev[0]][prev[1]] = 8
        

    print(len(locations))

    count = 0
    for i in range(len(locations)):
        for j in range(i):
            if locations[i][:2] == locations[j][:2]:
                break
        else:
            map[locations[i][0]][locations[i][1]] = 8
            count += 1
    print(count)
    
while True:

    loc = find_smallest()
    if max(location_cost[goal_y, goal_x]) > 0:
        print('y')
        if min(location_cost[goal_y, goal_x]) <= location_cost[loc]:
            print(location_cost[goal_y, goal_x]); break
    #print(location_cost[:, :, 0])
    update(find_smallest())

reconstruct()

print('')
for line in map:
    for char in line:
        print({0: " ", 1: "O", 8: "+"}[char], end='')
    print('')
print('')




print('')

for line in map:
    for char in line:
        print({0: " ", 1: "O", 8: "+"}[char], end='')
    print('')
print('')


for y in range(ny):
    for x in range(nx):
        if map[y][x] == 1:
            print("0",end='')
        elif min(location_cost[y,x,:]) > 0:
            print("+",end='')
        else:
            print(".",end='')
    print('')
print('')



counter = 0
for y in range(ny):
    for x in range(nx):
        if map[y][x] == 8:
            counter += 1
print(counter)


[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 1 1 0 1 0 1 1 1 0 1]
 [1 0 0 0 0 0 1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 1 1 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 0 0 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 1 0 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [1 1 1 0 1 0 1 1 1 1 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 0 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 1 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 1 0 0 0 1 0 1 0 1]
 [1 0 1 1 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 0 0 1 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
(15, 15, 4)
y
[7036 8036 9036 8036]
[(1, 13, 0)]
[(2, 13, 0)]
[(3, 13, 0)]
[(4, 13, 0)]
[(5, 13, 0)]
[(6, 13, 0)]
[(7, 13, 0)]
[(8, 13, 0)]
[(9, 13, 0)]
[(10, 13, 0)]
[(11, 13, 0)]
[(12, 13, 0)]
[(13, 13, 0)]
[(13, 12, 1)]
[(13, 11, 1)]
[(12, 11, 2)]
[(11, 11, 2)]
[(10, 11, 2)]
[(9, 11, 2)]
[(8, 11, 2)]
[(7, 11, 2)]
[(7, 10, 1)]
[(7, 9, 1)]
[(7, 8, 1)]
[(7, 7, 1)]
[(7, 6, 1)]
[(7, 5, 1)]
[(8, 5, 0), (7, 4, 1)]
[(8, 5, 0), (7, 3, 1)]
[(8, 5, 0), (8, 3, 0)]
[(8, 5, 0), (9, 3, 0)]
[(8, 5, 0), (10, 3, 0